### ISSUE TITLE
Failed Run: no .db files in the specified directory to read

### ISSUE THREAD

**Issue by tuliscot** [femiguez/apsimx#80] opened 2021-12-05 18:47 UTC
Hi APSIMers,
 
Was trying to run an example Soybean simulation  and i am getting these 2 errors: 1 FATAL and 1 WARNING. Please HELP!

FATAL ERROR
Error in read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  : 
  There are no .db files in the specified directory to read.

WARNING ERROR
In addition: Warning messages:
1: In auto_detect_apsimx() : Multiple versions of APSIM-X installed. 

                    Choosing the newest one: APSIM2021.10.11.6842
2: In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2021.10.11.6842\bin\Models.exe C:\Users\xxx\OneDrive\Documents\R\win-library\4.0\apsimx\extdata\Soybean.apsimx' had status 32899

Please help

**Comment by femiguez** [comment] 2021-12-05 19:10
It is possible that you do not have permission to run APSIM at C:\Users\xxx\OneDrive\Documents\R\win-library\4.0\apsimx\extdata\Soybean.apsimx. The warning is because you have multiple versions of APSIM Next Gen installed. You can turn this off using 'options'. If you just want to test it try

```
library(apsimx)
apsimx_options(warn.versions = FALSE)
maize <- apsimx_example("Maize")
head(maize)
```

If you want to run the Soybean example, copy it to a location where you have read/write permissions.

**Comment by tuliscot** [comment] 2021-12-06 12:43
Thanks. Solved that but just got another bug. I just updated R and R Studio. Hope thats not the issue. Have attached the screenshot as well.
-------------------------------------------------------------------------------------------------------------------------------------
![APSIM_Run_Error](https://user-images.githubusercontent.com/84679885/144847966-737307ad-6c38-43b3-a8b8-5ea7ba510413.jpg)

Error in read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  : 
  No report tables found
In addition: Warning message:
In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2021.10.11.6842\bin\Models.exe C:\Users\Siyabusa\OneDrive\Documents\R\win-library\4.1\apsimx\extdata\Maize.apsimx' had status 32899

**Comment by femiguez** [comment] 2021-12-06 17:13
First, I suggest that you create a 'folder' where you work on this project. No spaces are allowed. So your path above 'C:/Users/Siyabusa/OneDrive - CGIAR/EiA/Scripts/' won't work unless you delete the spaces in 'OneDrive - CGIAR'. After you do this, try this code:

```
library(apsimx)
apsimx_options(warn.versions = FALSE)

ex.dir <- auto_detect_apsimx_examples()
file.copy(file.path(ex.dir, "Soybean.apsimx"), ".")

soy <- apsimx("Soybean.apsimx")
```

You should not be trying to run APSIM examples directly from the 'extdata' folder. One possible workflow is to open an example in the APSIM Next Gen GUI, make some changes and then run this example from R making edits as needed.

**Comment by femiguez** [comment] 2022-01-05 20:15
I will close this for now, let me know if you have any other issues

**Closed by femiguez** 2022-01-05 20:15 UTC

**Comment by andynen** [comment] 2022-12-15 01:43
Hello @femiguez following up on this issue. 

I recently came accross the same challenge when running APSIMX on an HPC. I was advised to change file permission using the chmod command. In R the function is Sys.chmod (more info here https://stat.ethz.ch/R-manual/R-devel/library/base/html/files2.html). 

For anyone who might run into the same - I used the following commands to change file permissions on my apsimx file and all the file in the bin folder of the apsimx installation folder (just to be on the safe side). 

# apsim sim file
Sys.chmod( paste0(wd, "/APSIM_R/APSIM_file.apsimx"), "777")

# bin folder
files = list.files( path = paste0(wd, "/MyRlibs/APSIM2022.11.7125.0/bin") )
for( f in files){
   Sys.chmod( paste0(wd, "/MyRlibs/APSIM2022.11.7125.0/bin/", f ), "777")
}

However, I still got the same error (also see the image - portion covered by the red line)
          ```
                _sh: /project/RDS-FAE-NatDSM-RW/AndreeNM/Crop_modelling/MyRlibs/APSIM2022.11.7125.0/bin/: is a directory
                Error in read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  :
                  No report tables found
                In addition: Warning messages:
                1: In auto_detect_apsimx() :
                  APSIM-X not found, but a custom one is present
                2: In system(command = run.strng, ignore.stdout = silent, intern = TRUE) :
                  running command '/project/RDS-FAE-NatDSM-RW/AndreeNM/Crop_modelling/MyRlibs/APSIM2022.11.7125.0/bin/ 
            /project/RDS-FAE-NatDSM-RW/AndreeNM/Crop_modelling/APSIM_R/APSIM_Template_25Nov22.apsimx --verbose' had 
           status 126_
          ```

**But when I use the function process from the package "processx", it runs perfectly fine and it also writes the db file in the designated folder (see image below - portion covered by the blue line).** 
 
I looked at the apsimx function - and I was wondering if there is something missing when the os.type is unix? 

**Any idea what the issue is with the apsimx function and how to resolve it?**

Thank you, 
A

![image](https://user-images.githubusercontent.com/68366659/207751018-862019ac-a94d-4ac6-bf3b-eaae566cd02d.png)
