### ISSUE TITLE
Error running APSIMx files

### ISSUE THREAD

**Issue by Janewanguimugo** [femiguez/apsimx#117] opened 2023-02-27 13:17 UTC
I am no longer able to run any apsimx simulations even those that come with package. What could be the error?
For example this returns an error
extd.dir <- system.file("extdata", package = "apsimx")
sim <- apsimx("Wheat.apsimx", src.dir = extd.dir, value = "report")

Error in read_apsimx(file = sub("apsimx$", "db", file), src.dir = src.dir,  : 
  There are no .db files in the specified directory to read.
In addition: Warning message:
In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2023.2.7166.0\bin\Models.exe C:\Users\Admin\AppData\Local\R\win-library\4.2\apsimx\extdata\Wheat.apsimx' had status 32908

**Comment by Janewanguimugo** [comment] 2023-02-27 14:12
The error occurred today, everything was alright before. How can I install
an older version?

**Comment by femiguez** [comment] 2023-02-27 15:02
From the APSIM download page select an older version of the software. You might need to increase the number of entries shown

**Comment by Janewanguimugo** [comment] 2023-02-28 07:12
Thank you it worked. On a different matter is there an issue with the soil download (get_isric_soil_profile())? I am trying to download soils for 800 points to do a spatial simulation. I get results of my simulation in some points and errors in others. eg. an issue with soil LL in one site and maybe soil SAT in another. Is there any way to get the correct soil without errors?

**Comment by femiguez** [comment] 2023-02-28 14:38
The version in github has an option 'fix' that will try to correct these errors before they are detected by APSIM. Set 'fix' to TRUE (default is FALSE). Let me know if that works

**Comment by Janewanguimugo** [comment] 2023-03-09 07:16
When I used fix = TRUE, I am running potato simulations btw...I got results for approximately 500 locations, the others still have soil issues. Does it mean I now have to fix the unique issues one by one? Or is there any way to get the correct soil for the 800 points at once.

**Comment by femiguez** [comment] 2023-03-09 17:00
What does the error message look like? I could include code that addresses this issue before you run the simulations

**Comment by Janewanguimugo** [comment] 2023-03-10 07:06
It's a soil issue when I check in the GUI. I have attached the file for the location with an error...most locations have no issues. The error when running in R is the one below.

Error in read_apsimx(file = sub("apsimx$", "db", file), src.dir = src.dir,  : 
  No report tables found
In addition: Warning message:
In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2022.12.7129.0\bin\Models.exe .\PotatoFactorialFebMAr.apsimx' had status 1

[PotatoFactorialFebMAr.zip](https://github.com/femiguez/apsimx/files/10939467/PotatoFactorialFebMAr.zip)

**Comment by femiguez** [comment] 2023-03-30 17:27
The problem is that LL can't be lower than AirDry. I have made this change to my 'fix' function, but it is not public yet. You can try using it

````
fix_apsimx_soil_profile <- function(x, soil.var = c("SAT", "BD"), particle.density = 2.65, verbose = TRUE){
  
  if(!inherits(x, "soil_profile"))
    stop("object should be of class 'soil_profile'", call. = FALSE)
  ## Heuristics for fixing soil profiles
  
  soil.var <- match.arg(soil.var)
  
  ## Bulk density and saturation issue
  max_bd <- (1 - x$soil$SAT) * 2.65
  bd_diff <- max_bd - x$soil$BD
  
  for(j in seq_along(max_bd)){
    if(bd_diff[j] <= 0){
      x$soil$SAT[j] <- 1 - x$soil$BD[j] / 2.65 - 0.001
      if(verbose && soil.var == "SAT"){
        cat("Saturation of:", x$soil$SAT[j], "in layer:", j, "was above acceptable value of:", 1 - x$soil$BD[j] / 2.65, ".",
            "It was adjusted to:", 1 - x$soil$BD[j] / 2.65 - 0.001, "\n")              
      }
      ## Fixing LL and air dry issue
      if(x$soil$LL15 < x$soil$AirDry){
        if(verbose){
          cat("LL15 cannot be lower than AirDry in layer:", j,".\n",
              "It was adjusted to the value of AirDry.\n")
        }
        x$soil$LL15[j] <- x$soil$AirDry[j]
      }
    }
  }
  return(x)
}
````

**Comment by Janewanguimugo** [comment] 2023-03-30 17:34
Thank you, I shall give it a try

**Comment by Janewanguimugo** [comment] 2023-04-20 08:08
Hello,
So I used the fix function and now I am encountering new issues. Kindly see the attached file, it is a soil issue as well. The issue keeps changing depending on the site.

[example_file.zip](https://github.com/femiguez/apsimx/files/11283891/example_file.zip)

**Comment by femiguez** [comment] 2023-12-18 22:10
@Janewanguimugo Have you been able to figure this out? There are some issues which pertain to APSIM Next Gen, which are not related to the apsimx R package. I know there is an issue with initial water. I'm going to close this to concentrate on other issues. Let me know if you still need help

**Closed by femiguez** 2023-12-18 22:10 UTC
