### ISSUE TITLE
Apsim doesn't work in Mac. Cil Image error

### ISSUE THREAD

**Issue by overg123** [femiguez/apsimx#57] opened 2021-09-13 15:24 UTC
Hi,

I tried to install ApsimX using the documents provided, and no matter what I try to do I receive this error when I try to run the mono models ./Wheat.apsimx:
open assembly 'models': File does not contain a valid CIL image.

Any ideas on how to solve this issue?

**Comment by femiguez** [comment] 2021-09-13 15:55
It looks to me like you are trying to run APSIM through the command line. The R package 'apsimx' is used to run APSIM through R. What happens when you open R and type `library(apsimx)`? Do you get any messages?

**Comment by overg123** [comment] 2021-09-13 16:03
HI,

Thanks for the quick response!

Indeed, I tried to check APSIMX in the command line first, before trying the R option ( as recommended by one of the documents I read ).

Btw, when I try to run in R env I get:

Error: package or namespace load failed for 'apsimx' in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/apsimx/R/apsimx.rdb' is corrupt

**Comment by femiguez** [comment] 2021-09-13 16:14
Did you install apsimx from CRAN or from github? Try re-installing apsimx from CRAN.

**Comment by overg123** [comment] 2021-09-13 16:16
Yes.
Maybe there is a mix match in APSIMX dirs? 
I get this:
install.packages("apsimx")
trying URL 'https://ftp.osuosl.org/pub/cran/bin/macosx/contrib/4.1/apsimx_2.0.tgz'
Content type 'application/x-gzip' length 1296553 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/8j/7rx3z6gd5db4w7gx88gjv8v80000gn/T//RtmpLLygUA/downloaded_packages
> library(apsimx)
Error: package or namespace load failed for 'apsimx' in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/apsimx/R/apsimx.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1

**Comment by femiguez** [comment] 2021-09-13 16:29
It might be that there is an error at the moment in CRAN. You can try downloading the tar.gz file (from here: https://cran.r-project.org/package=apsimx) and installing directly. Let me know if you do not know how to do this.

**Comment by overg123** [comment] 2021-09-13 16:43
Tried it, and it sill doesn't work.


install.packages("/Users/odedperry/Desktop/apsimX/apsimx/R/apsimx" ,repos = NULL, type = "source")
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
Error in getOctD(x, offset, len) : invalid octal digit
Warning message:
In install.packages("/Users/odedperry/Desktop/apsimX/apsimx/R/apsimx",  :
  installation of package '/Users/odedperry/Desktop/apsimX/apsimx/R/apsimx' had non-zero exit status
> library(apsimx)
Error: package or namespace load failed for 'apsimx' in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/apsimx/R/apsimx.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
>

**Comment by femiguez** [comment] 2021-09-13 18:12
That looks like an R issue unrelated to the R package apsimx or APSIM. If possible, I would try to re-install R, because I suspect that you will have this problem with other packages as well. Is this the case?

**Comment by hol430** [comment] 2021-09-13 22:37
> File does not contain a valid CIL image.

I don't know anything about the R package problems, but this particular error from your initial comment could be caused by trying to run a self-contained .net core assembly with mono. Try omitting the `mono` command and just running Models (I'm assuming it's got execute permissions?).

Recent (and future) versions of apsim on mac/linux do not require mono, as they run on the .net core runtime.

**Comment by overg123** [comment] 2021-09-14 06:37
> > File does not contain a valid CIL image.
> 
> I don't know anything about the R package problems, but this particular error from your initial comment could be caused by trying to run a self-contained .net core assembly with mono. Try omitting the `mono` command and just running Models (I'm assuming it's got execute permissions?).
> 
> Recent (and future) versions of apsim on mac/linux do not require mono, as they run on the .net core runtime.

The mono ( at least on my Mac ) is a must  :)

And I managed to run it using this command:
mono /Applications/APSIM2021.8.31.6677.app/Contents/Resources/bin/Models.exe Wheat.apsimx

Now I need to solve the R issues :)

**Comment by femiguez** [comment] 2021-09-14 11:37
@hol430 Thanks for the comment. I have on my to-do list upgrading to dotnet, but the current version of APSIM does not run on Mac. (I will test on linux later). I posted an issue on APSIMX. 
@overg123 That is the command that the R package will send (when properly installed).

**Comment by femiguez** [comment] 2021-10-03 12:41
I'm closing this. Please feel free to open a new issue.

**Closed by femiguez** 2021-10-03 12:41 UTC
