### ISSUE TITLE
Missing DLL when running Model.exe  from command line

### ISSUE THREAD

**Issue by juancrescente** [femiguez/apsimx#72] opened 2021-11-11 17:23 UTC
In Windows 10

I have APSIM installed and I have the binaries of APSIMX and I got the following error:
`
CompletedProcess(args='C:/Users/taora/APSIM2021.11.9.6934/bin/Models newmodel.apsimx', returncode=3762504530, stdout="----------------------------------------------\nSystem.Exception: Error in file:C:\\Users\\taora\\models_python\\data\\newmodel.apsimx\n ---> System.Exception: Error reading file C:\\Users\\taora\\models_python\\data\\newmodel.apsimx\n ---> System.DllNotFoundException: Unable to load DLL 'fbclient.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)\n at Models.Core.Run.SimulationGroup.<>c.<Initialise>b__28_0(Exception e)\n at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName)\n at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground)\n --- End of inner exception stack trace ---\n at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground)\n at Models.Core `

**Comment by femiguez** [comment] 2021-11-11 17:58
It is likely that at least part of the issue is that you should install apsimx from github. So if you have 'remotes'

```
remotes::install_github("femiguez/apsimx")
```
However, those errors suggest that there might be something else going on with APSIM Next Gen.
Can you try again after that and report back?

**Comment by femiguez** [comment] 2021-11-17 22:24
I'll close this by https://github.com/APSIMInitiative/ApsimX/issues/6948. Let me know if you need help with anything else.

**Closed by femiguez** 2021-11-17 22:24 UTC
