### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by hol430** [femiguez/apsimx#2] opened 2019-10-14 01:54 UTC
Hi @femiguez, I have a couple of questions about this package, although I should first say that I don't know much about R.

- I'm able to run an example (factorial example) using my custom build version of apsim but inside the returned data the Simulations table is called Simualtions - is this a typo? I'm assuming there is some sort of name translation going on here as it's called _Simulations in the .db file.

- If I try to use the inspect_apsimx function I get an error:

```R
inspect_apsimx('Factorial.apsimx', src.dir = 'C:/ApsimX/Examples', node = 'Clock')
Error in inspect_apsimx_json(file = file, src.dir = src.dir, node = node,  : 
  could not find function "read_json"
```

- I've just added a feature to apsim which will allow for basic editing of an .apsimx file from the command line. See APSIMInitiative/ApsimX#4264 for more details but the basic idea is that you just call Models.exe and pass in the path to your .apsimx file and a config file which contains several path = value lines, and apsim will go through the config file and apply the changes listed there. The advantage of using this feature is that it won't break if we change the .apsimx file format. e.g. I see that this apsimx R library assumes that there is a node under soil called "Water", but this node was recently renamed to Physical.

**Comment by femiguez** [comment] 2019-10-14 10:52
Hi @hol430 Thank you for your interest in apsimx! 

Which version of APSIMX are you running? I'm using Mac and ApsimX 4200. If I run the Factorial example (distributed with ApsimX) and it produces a Factorial.db file as expected. I don't do any renaming of files, so if this was done, it was done by R because it does not allow for a file to start with '_'. I tried this in Mac, and R didn't do any renaming. Perhaps it is a Windows specific thing. If you want to give me a different specific example, I can include it with the package and run it as a test.

That error message suggests to me that you did not install the 'apsimx' R package in a standard way. The function 'read_json' exists inside 'jsonlite' which is an R package that should either already be installed or installed at the same time as you install 'apsimx'. Did you use this command to install apsimx?

> library(devtools)
> devtools::install_github("femiguez/apsimx")
> library(apsimx)

If you install 'apsimx' from source, you should install these packages manually first.

DBI, jsonlite, knitr, RSQLite, xml2

Thanks for that new feature. I'll see how best to implement it. A user can always write a script from scratch to edit the JSON file, but my goal with the package is to make it easy to edit the file from within R. I'm guessing this feature is platform independent? I have realized that the 'inspect' and 'edit' files are 'fragile' but I would expect them to stabilize when 'ApsimX' stabilizes.

I appreciate all the work you are doing!

Best,

Fernando

**Comment by hol430** [comment] 2019-10-14 22:21
Hey Fernando -

My apsimx version is a custom build which should correspond roughly to the latest official released version. If I use the `apsimx_options()` function to change to using an official release (2019.09.11.4048), I still see the same behaviour.

I'm not seeing any files renamed when I run the factorial example - what I see is a typo in the name of the Simulations table returned by the `apsimx()` function. I think it may be due to [this line](https://github.com/femiguez/apsimx/blob/master/R/apsimx.R#L369) in `apsimx.r` (see typo in the word Simulations on this line). It's pretty minor issue so I'm not too concerned with this one either way.

As far as I know (I'm certainly not an R expert) I installed this apsimx package in the standard way with `devtools::install_github('femiguez/apsimx')`. I don't know if jsonlite was installed or not but I ran `packages.install('jsonlite')` to install it and I still get the same error:

```r
> library('apsimx')
> library('jsonlite')
> packageVersion('apsimx')
[1] ‘0.84’
> packageVersion('jsonlite')
[1] ‘1.1’
> inspect_apsimx('Factorial.apsimx', src.dir = 'C:/ApsimX/Examples', node = 'Clock')
Error in inspect_apsimx_json(file = file, src.dir = src.dir, node = node,  : 
  could not find function "read_json"
```

wrt the new feature, a user can write a script from scratch to edit the json but the script is liable to break if they upgrade to a newer version of ApsimX. A

**Comment by femiguez** [comment] 2019-10-15 12:23
@hol430 Thanks! The typo was easy to fix once you pointed me in the right direction. I'm currently adding some testing to the package to catch errors as I install new versions of APSIM-X. Notice that the apsimx R package is at version 1.07 now. I will get bak to you after I implement the new testing.

**Comment by femiguez** [comment] 2019-10-16 14:52
@hol430 Hi Drew, This is my update:

1) Several examples distributed with ApsimX use relative paths for the .met files such as %root%...\WeatherFiles\...met and I can run these examples fine. The ones which do not use relative paths and use simply 'WeatherFiles\lincoln.met' (Factorial example) are problematic because if I move them (copy them to a different directory) ApsimX can't find the files. Would it be possible to use relative paths for all the examples?

2) The 'Factorial' example is tricky because if you open it in the GUI it looks like it is only using 'lincoln.met' but when I run the example in the command line, it throws an error because it is also pointing to 'Dalby.met' (LN 3061) and 'Goond.met' (LN 3087). If I inspect the file using the GUI I can't find these. It returns an error for simulations 32 and 35. I can still run it with 'apsimx' despite these errors.

3) I included code in directory 'tests' that can run the 'Factorial' example and it shows how to inspect it using 'inspect_apsimx_replacement'. It edits the path to the '.met' file for 'lincoln.met' but it does not catch those instances for 'Dalby.met' and 'Goond.met'. 

4) Your error about not finding 'read_json' is puzzling because I can't reproduce it. One of the possible sources of this error should go away if you re-install the 'apsimx' R package. To install the 'vignettes' use:

> devtools::install_github("femiguez/apsimx", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)

To access the vignettes (in R):

> vignette("apsimx")
> vignette("apsimx-scripts")

Search in the 'vignette' for the 'Factorial' example.

Thanks for testing the package. It is helping me improve it. Let me know if this helps or if you have other questions.

Best,

Fernando

**Comment by frank0434** [comment] 2019-10-17 00:22
Hi @femiguez 

I have the same goal as you mentioned. 
currently, I wrote a very specific R script to modify the one apsimx file and produce many so that we can run all the apsimx file in the clusters simultaneously.

the R script is very restricted, I have to modify the one base apsimx file to meet the code structure requirements. the structure shows below.

```
  layer1 <- which(rlist::list.mapv(base_apsim$Children, Name)== simulationExp)
  layer2 <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children, Name)== rotation)
  weather.pos <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children[[layer2]]$Children, Name) == weather)
  clock.pos <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children[[layer2]]$Children, Name) == clock)
  block.pos <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children[[layer2]]$Children, Name)==block)
  manager.pos <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children[[layer2]]$Children[[block.pos]]$Children, Name)==managerfolder)
  factor.pos <- which(rlist::list.map(base_apsim$Children[[layer1]]$Children[[layer2]]$Children[[block.pos]]$Children[[manager.pos]]$Children, Name)==factorlabels)
```
i'm wondering what is the strategy you use to modify the json file in R? 
i've tried to unserialise the json first and serialise it back after the modification. but the json structure is never the same like the original one, which can't be opened by apsimx anymore. 


_'A user can always write a script from scratch to edit the JSON file, but my goal with the package is to make it easy to edit the file from within R. I'm guessing this feature is platform independent? I have realized that the 'inspect' and 'edit' files are 'fragile' but I would expect them to stabilize when 'ApsimX' stabilizes.'_

**Comment by femiguez** [comment] 2019-10-17 01:10
Hi @frank0434 ! Can you try installing the latest version (1.21) of the apsimx package and reading the vignette? As it is, it might meet your needs, but let me know if you have any questions.

Use this:
devtools::install_github("femiguez/apsimx", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)

Yes, the code you are using is not very robust. :)

**Comment by frank0434** [comment] 2019-10-17 02:49
Thanks for the advice, @femiguez 
got this error during the installation. 
wondering which `example files` that I missed. 
Do have to install this package in the same directory as the `APSIMX`? 

I am also using a custom build version of apsimx. 
```
E  creating vignettes (6.3s)
   --- re-building 'apsimx-scripts.Rmd' using rmarkdown
   --- finished re-building 'apsimx-scripts.Rmd'
   
   --- re-building 'apsimx.Rmd' using rmarkdown
   Quitting from lines 84-89 (apsimx.Rmd) 
   Error: processing vignette 'apsimx.Rmd' failed with diagnostics:
   cannot find example files
   --- failed re-building 'apsimx.Rmd'
   
   SUMMARY: processing the following file failed:
     'apsimx.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'apsimx' from GitHub:
  System command error, exit status: 1, stderr empty
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
```
https://github.com/femiguez/apsimx/blob/ed8e6b1e8a0c2a6949aff820dd4a048d65bc4678/doc/apsimx.Rmd#L84-L89

**Comment by femiguez** [comment] 2019-10-17 10:53
@frank0434 It sounds like in your custom build of ApsimX you have removed the 'Maize' example. That is why building the vignette fails.

**Comment by femiguez** [comment] 2019-10-27 13:25
@frank0434 Have you been able to build the package and the vignettes once you have a distributed version of ApsimX installed?
@hol430 Drew, the only way I can reproduce your example is if I install first 'apsimx' and then I 'source' the function 'inspect_apsimx' and then try to run it, but this does not agree with the order in which you presented your code. If you load the 'jsonlite' library (which is not necessary) I can't see how you can possibly get the error 'could not find function read_json'. BTW, I created the function 'edit_apsimx_batch' based on the new feature, but have not tested it at all yet.

**Comment by hol430** [comment] 2019-10-27 23:32
Hi Fernando,

Sorry it's taken a while to get back to you. I'm still getting the same error as above. If I open R studio with no functions/libraries sourced or loaded and then run the same commands I posted above I get that result. I wonder if it's due to me using an old version of this package - although it's a strange error to be getting! Anyway I thought I'd try and upgrade to the lastest version of this package to make things simpler but I get an error:

```
> devtools::install_github('femiguez/apsimx')
Downloading GitHub repo femiguez/apsimx@master
from URL https://api.github.com/repos/femiguez/apsimx/zipball/master
Installing apsimx
"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/hol430/AppData/Local/Temp/RtmpgnCHfM/devtools42642ff4681/femiguez-apsimx-68fd848"  \
  --library="C:/Users/hol430/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'apsimx' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : undefined exports: apsim_version
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/hol430/Documents/R/win-library/3.3/apsimx'
* restoring previous 'C:/Users/hol430/Documents/R/win-library/3.3/apsimx'
Error: Command failed (1)
```

**Comment by femiguez** [comment] 2019-10-28 00:25
@hol430 Forgot to add the new apsim_version to github. I just fixed that issue.

**Comment by hol430** [comment] 2019-10-28 05:42
Hi Fernando - Thanks to your fix I can now upgrade to the latest version of this package. However if I try to build the vignettes via the syntax you posted above, I get this error:

```r
> devtools::install_github("femiguez/apsimx", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE, force = TRUE)
Downloading GitHub repo femiguez/apsimx@master
from URL https://api.github.com/repos/femiguez/apsimx/zipball/master
Installing apsimx
"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  "C:\Users\hol430\AppData\Local\Temp\RtmpM1D4yN\devtools435060c62360\femiguez-apsimx-bbee551" --no-resave-data --no-manual 

* checking for file 'C:\Users\hol430\AppData\Local\Temp\RtmpM1D4yN\devtools435060c62360\femiguez-apsimx-bbee551/DESCRIPTION' ... OK
* preparing 'apsimx':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
Warning: namespace 'evaluate' is not available and has been replaced
by .GlobalEnv when processing object ''
Error: processing vignette 'apsimx-scripts.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because apsimx-scripts.Rmd appears to be an R Markdown v2 document.
Execution halted
Error: Command failed (1)
```

**Comment by femiguez** [comment] 2019-10-28 11:01
Hi Drew @hol430 . This is helpful and I think it begins to explain why you were getting the previous error too. In both cases apsimx cannot find other packages that it depends on. In the first case, it was 'jsonlite' and in this case it is 'knitr'. The reason is a mismatch between your server and your local system. I see that you have:

R Server:
C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R

And Local system:
C:\Users\hol430\AppData\Local

I don't know much about Windows because I do all of my research in Mac/Linux, but there are some options I can think of to resolve this. If you want to run R exclusively on the server you might not be able to use 'install_github' (unless you do this on the server instead of your local system, maybe(?)). Unless I missed this, by looking at the docs I don't see control for where to install using 'install_github'. The way I have controlled this in the past is by using 

> install.packages("path/to/apsimx/tarball", lib = "path/to/where/you/want/to/install", repos = NULL, type = "source")

See ?install.packages in R for more details.

When you load the library in R you might need to specify the path

> library("aspimx", lib.loc = "path/to/where/it/was/installed")

I would guess that this should be a problem for other packages and not only for mine. You can control globally some of these options by having an '.Rprofile' file in your home directory and specifying '.libPaths'.

If my guess is correct, you can either download all the files from github and build the package manually or for this instance here is the source:

https://www.dropbox.com/s/c8djjnyy988oo8y/apsimx_1.41.tar.gz?dl=0

I will add to my 'to-do' list creating a website with resources.

Let me know how it goes.

Fernando

**Comment by frank0434** [comment] 2019-10-29 01:10
@femiguez thanks for the following up and sorry for the late reply. 

I can install the package without building the vignette for the custom build version apsimx. 
Haven't got a chance to properly use it. 

I just found out the old link I had in the email is no longer working anymore for downloading distributed version. Will try it again once I have the distributed version. 
Thank you.

**Comment by femiguez** [comment] 2019-10-29 01:44
Okay, since building the vignettes is a bit of a pain for everyone. I have now published them here: https://femiguez.github.io/apsimx-docs/

**Comment by femiguez** [comment] 2020-07-06 11:49
The package is now on CRAN. I will close this issue, but if you have any comments, questions or issues, I'll open a new one. Thanks!

**Closed by femiguez** 2020-07-06 11:49 UTC
